### ISSUE TITLE
Newer Cosmetics Issue 

### ISSUE THREAD

**Issue by minein4** [juliarose/tf2-item-context-search#1]
Hello, 
Just a small issue nothing that bad just an issue with new cosmetics with the extension not allowing you to look up newer cosmetics since its not in the extension's item schema. I tried looking up Combat Casual which was released on July 29, 2022 the summer 2022 update. 

![image](https://user-images.githubusercontent.com/54459373/209948291-5a735417-7b60-43b9-9ff8-236aefb55dd2.png)

Any idea when/if the item schema will get updated?

Thanks
Ichigo

**Comment by juliarose** [comment]
This is due to an external schema file which I maintain. I have updated it now. The new items should load into the extension now but it may take up to a day for it to update.
